server:
  port: 80

swagger:
  basePackage: com.sunflower.springcloud
  title: "springcloud"
  description: "microservicecloud-consumer-dept-80"
  contactName: "微服务消费者"

eureka:
  client:
    register-with-eureka: false  #自己不注册到eureka服务上
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

ribbon:
  MaxAutoRetries: 1



